version: '3.4'

services:
  beboerweb.api:
    image: rasmus5500/beboerwebapi:latest
    build: .
    ports: 
      - 6001:80

  beboerweb.mvc:
    image: rasmus5500/beboerwebmvc:latest
    build: .
    ports: 
      - 5001:80
